version: "3.4"

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=meditation
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data: